apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: staging
resources:
  - ../../base
  - namespace.yaml
  - release.yaml
  - db-cluster.yaml
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
  - name: ghost-db-config
    literals:
      - DB_HOST=ghost-mysql.staging.svc.cluster.local
      - DB_USER=ghost
      - DB_NAME=ghost
      - DB_PORT=3306
